[package]
name = "rust_ai"
version = "0.1.0"
edition = "2021"

[dependencies]

candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.7.2", features = ["cuda"] }
hf-hub = { version = "0.3.2", features = ["tokio"] }
